document.writeln("<style type=\"text\/css\">");
document.writeln(".ZyiisWin * {");
document.writeln("	-moz-box-sizing : border-box;");
document.writeln("}");
document.writeln(".ZyiisWin {");
document.writeln("	text-align: left;");
document.writeln("}");
document.writeln(".ZyiisWinTitleArea {");
document.writeln("  font-family: \"Trebuchet MS\", Verdana, Arial , Heltvetica, sans-serif;");
document.writeln("  font-size: 13px;");
document.writeln("  font-weight: bold;");
document.writeln("  height: 28px;");
document.writeln("  cursor: default;");
document.writeln("  text-align:left;");
document.writeln("}");
document.writeln(" .ZyiisWinTitleArea td {");
document.writeln("  background: url("+img_url+"/titlebar_on_bg.gif) repeat-x right  top;");
document.writeln("}");
document.writeln(".ZyiisWinBack .ZyiisWinTitleArea td {");
document.writeln("  background: url("+img_url+"/titlebar_off_bg.gif) repeat-x right  top;");
document.writeln("}");
document.writeln(" #titleFirstCell {");
document.writeln("  background: url("+img_url+"/titlebar_on_left_corner.gif) no-repeat left  top;");
document.writeln("}");
document.writeln(".ZyiisWinBack #titleFirstCell {");
document.writeln("  background: url("+img_url+"/titlebar_off_left_corner.gif) no-repeat left  top;");
document.writeln("}");
document.writeln(" #titleLastCell {");
document.writeln("  background: url("+img_url+"/titlebar_on_right_corner.gif) no-repeat right  top;");
document.writeln("}");
document.writeln(".ZyiisWinBack #titleLastCell {");
document.writeln("  background: url("+img_url+"/titlebar_off_right_corner.gif) no-repeat right  top;");
document.writeln("}");
document.writeln(" #titleLastCell, .ZyiisWinBack #titleLastCell {");
document.writeln("  width : 13px;");
document.writeln("}");
document.writeln(".ZyiisWinTitleText {");
document.writeln("    white-space: nowrap;");
document.writeln("    padding-top: 5px;");
document.writeln("	padding-left : 6px;");
document.writeln("	color : #fff;");
document.writeln("}");
document.writeln(".ZyiisWinCloseButton, .ZyiisWinMinButton, .ZyiisWinMaxButton, .ZyiisWinRestoreButton {");
document.writeln("    height: 21px;");
document.writeln("    width: 21px;");
document.writeln("    margin-right: 3px;");
document.writeln("    margin-top:3px;");
document.writeln("}");
document.writeln(" .ZyiisWinCloseButton{");
document.writeln("  background: url("+img_url+"/close.gif);CURSOR:pointer ");
document.writeln("}");
document.writeln(".ZyiisWinBack .ZyiisWinRestoreButton {");
document.writeln("	background: url("+img_url+"/restore_inactive.gif) no-repeat 0 0;");
document.writeln("}");
document.writeln(".ZyiisWin #contentCell {");
document.writeln("	border-left-width : 1px;");
document.writeln("	border-right-width : 1px;");
document.writeln("	border-left-style : solid;");
document.writeln("	border-right-style : solid;");
document.writeln("	padding : 0px 3px 0px 3px;");
document.writeln("}");
document.writeln(" #contentCell {");
document.writeln("	border-left-color : #00138b;");
document.writeln("	border-right-color : #00138b;");
document.writeln("	background-color : #0855dd;");
document.writeln("}");
document.writeln(".ZyiisWinBack #contentCell {");
document.writeln("	border-left-color : #5b5ec5;");
document.writeln("	border-right-color : #5b5ec5;");
document.writeln("	background-color : #7689d9;");
document.writeln("}");
document.writeln(".ZyiisWinContent {");
document.writeln("	background-color: #ffffff;");
document.writeln("	border-style: solid;");
document.writeln("	border-width: 1px;");
document.writeln("	border-color: #404040 #e0e0e0 #f0f0f0 #505050;");
document.writeln("	padding: 3px 2px 2px 3px;");
document.writeln("}");
document.writeln(".ZyiisWin #statusCell {");
document.writeln("	border-left-width : 1px;");
document.writeln("	border-right-width : 1px;");
document.writeln("	border-bottom-width : 1px;");
document.writeln("	border-left-style : solid;");
document.writeln("	border-right-style : solid;");
document.writeln("	border-bottom-style : solid;");
document.writeln("	padding : 0px 3px 3px 3px;");
document.writeln("}");
document.writeln(" #statusCell {");
document.writeln("	border-left-color : #00138b;");
document.writeln("	border-right-color : #00138b;");
document.writeln("	border-bottom-color : #00138b;");
document.writeln("	background-color : #0855dd;");
document.writeln("}");
document.writeln(".ZyiisWinBack #statusCell {");
document.writeln("	border-left-color : #5b5ec5;");
document.writeln("	border-right-color : #5b5ec5;");
document.writeln("	border-bottom-color : #5b5ec5;");
document.writeln("	background-color : #7689d9;");
document.writeln("}");
document.writeln(".ZyiisWinStatus {");
document.writeln("	height: 21px;");
document.writeln("    line-height: 21px;");
document.writeln("	text-align:left;");
document.writeln("	background: url("+img_url+"/status.gif);");
document.writeln("	color:black;");
document.writeln("    vertical-align: middle;");
document.writeln("    font-family: Arial, Heltvetica, Verdana, sans-serif;");
document.writeln("    font-size: 11px;");
document.writeln("    white-space: nowrap;");
document.writeln("    padding-left: 3px;");
document.writeln("}");
document.writeln(".ZyiisWinResize {");
document.writeln("	width: 13px;");
document.writeln("  	height: 21px;");
document.writeln("	background: url("+img_url+"/resize.gif) no-repeat top right;");
document.writeln("}");
document.writeln("<\/style>");
document.writeln("<DIV class=\" ZyiisWinFront\" style=\"Z-INDEX: 5; LEFT: "+((screen.width-vir_width)*0.5)+"px; WIDTH: "+vir_width+"px; height: "+vir_height+"px;POSITION: absolute; TOP: "+((screen.height-vir_height)*0.5/2)+"px;\" id=Zyiis_union >");
document.writeln("<DIV class=ZyiisWin>");
document.writeln("<TABLE cellSpacing=0 cellPadding=0 border=0>");
document.writeln("<TBODY>");
document.writeln("<TR class=ZyiisWinTitleArea>");
document.writeln("<TD id=titleFirstCell >");
document.writeln("<DIV >&nbsp;<\/DIV><\/TD>");
document.writeln("<TD  width="+(vir_width-5)+">");
document.writeln("<DIV class=ZyiisWinTitleText style=\"OVERFLOW: hidden; \" >"+vir_TitleText+"<\/DIV><\/TD>");
document.writeln("<TD id=titleLastCell >");
document.writeln("<DIV class='ZyiisWinCloseButton' style=\"OVERFLOW: hidden\" onclick=\"Zyiis_union.style.display='none'\" id='co'><\/DIV><\/TD><\/TR>");
document.writeln("<TR>");
document.writeln("<TD id=contentCell colSpan=5>");
document.writeln("<DIV class=ZyiisWinContent ><SPAN>"+vir_url+"<\/SPAN><\/DIV><\/TD><\/TR>");
document.writeln("<TR >");
document.writeln("<TD id=statusCell colSpan=5 >");
document.writeln("<TABLE id=statusTable height=\"100%\" cellSpacing=0 cellPadding=0 width=\"100%\" >");
document.writeln("<TBODY >");
document.writeln("<TR >");
document.writeln("<TD style=\"VERTICAL-ALIGN: bottom; WIDTH: 100%\" >");
document.writeln("<DIV class=ZyiisWinStatus style=\"OVERFLOW: hidden;\" ><\/DIV><\/TD>");
document.writeln("<TD style=\"VERTICAL-ALIGN: bottom\" >");
document.writeln("<DIV class=ZyiisWinResize style=\"OVERFLOW: hidden\" ><\/DIV>");
document.writeln("<\/TD><\/TR><\/TBODY><\/TABLE><\/TD><\/TR><\/TBODY><\/TABLE><\/DIV><\/DIV>");
function c_vir_pop(){
a=new Image();	
a.src=var_zY_Url;
document.getElementById('co').className='ZyiisWinCloseButton';
}
function c_vir_on(){
setTimeout("c_vir_pop()",5000);
}
