<?php 
$m = array
(	
	'register_err' => '系统无法提交您的注册信息，请确认是否正确的填写',
	'login_lock' =>'当前用户已被锁定',
	'login_email_lock' =>'用户还未激活，请查收您的电子邮箱，我们给您发送了激活邮件',
	'login_lock_0' =>'用户还未激活，请等待管理员审核一般在三天左右',
	'login_err' => '您输入的用户名或是密码错误，请重新登录',
	'checkcode' => '您输入的验证码和系统产生的不一致，请重新输入…',	
	'closeaffreg' => '联盟已停此会员注册',	
	'closeadvreg' => '联盟已停此广告商注册',	
	'answer_err' => '回答问题不能匹配',	
	'findpwd_succeed' => '系统成功接受了您的请求，新密码已发送到您的邮箱',	
	'activate_succeed' => '验证成功，请点击登录获取代码',	
	'activate_err' => '无法验证，未知',	
	'no_siteck' => '网站无法验证，请返回重新填写域名并验证',	
	'reaccountname' => '收款人已被注册，请不要重复注册',	
	're_username' => '重复的用户名，请重新输入',
	'history_back' => '正在跳转，请稍候...',	
	
	'not_web_webtype' => '最少需要选择一个网站类型,否则请选择在所有类目投放',
	'not_web_city' => '最少需要选择一个地区！否则请选择在所有地方显示',
	'not_web_time' => '最少需要选择一个时区！否则请选择全天投放',
	'not_web_weekday' => '最少需要选择一个星期值！否则请选择全星期投放',
	'not_value' => '请填写名称，价格，限额',
	'plan_add_succeed' => '计划新增完成',
	'not_adstype' => '新增广告出错！广告类型无法确认',
	'is_iframe' => '源代码中不能有内联框架或是js远程调用代码！',
	'min_oblprice' => '新价格不能低于旧价格，请重新输入',
	'create_plan_ok' => '新增计划成功，请等待我们审核，在审核时间您可以先发布广告！',
	'updateAds_ok' => '修改广告成功请等待管理审核通过',
	'upuserinfo_ok' => '修改信息成功',
	'notlink' => '当前类型直链没有开启，或是没有直链广告',
	'min_imoney' => '充值金额太小',
	
	'site_lock' => '网站未审核，无法新增广告位',
	'siteid_null' => '出现错误，未知的网站',
	'siteurl_num' =>'此域名已被提交过，请勿重提交！',
	'zonename_num' =>'广告位名称已提交过，请不要建立相同名称的广告位！',
	'no_ads_num' => '暂无广告可选择，请到广告列表查看！',
	're_choose_orders' => '不能重复提交已确认过的订单项',
	'no_cps_price' => '销售分成类单价不能为空，请您查看数据格式是否正确\n正确是:会员ID|结算数|反馈ID|价格|比例',
	'no_uid_int' => '数据格式中会员ID必须为整数',
	'no_num_int' => '数据格式中结算数必须为整数',
	'no_day' => '数据格式中日期不能为空',
	'no_linkuid_int' => '数据格式中反馈ID必须为整数',
	'no_data_han' =>'正确的完整格式是:会员ID|结算数|反馈ID|价格|比例\n注册类简写：会员ID|结算数',
	'null' =>'出现错误，未知的信息',
	
	'noacl' =>'最少需要选择一个可用的角色权限',
	'not_writeable' =>'生成的目录无法写入',
	'integral_status0' =>'基本设置中已关闭了积分功能',
);
?>